### ISSUE TITLE
Set up repository

### ISSUE THREAD

**Issue by darthmaim** [GW2Treasures/gw2tools#1]
- [x] add composer.json
- [x] publish on packagist
- [x] add readme
- [x] add license
- [x] setup phpunit
- [x] add automated travis builds
- [x] add automated test coverage
